packages:
  - packages/**
  - docs
catalog:
  "@curev/eslint-config": ^0.5.0
  "@iconify-json/carbon": ^1.2.8
  "@tanstack/virtual-core": ^3.13.6
  "@types/fs-extra": ^11.0.4
  "@types/node": ^22.15.12
  "@vitest/coverage-v8": ^3.1.3
  "@vue/test-utils": ^2.4.6
  bumpp: ^10.1.0
  defu: ^6.1.4
  eslint: ^9.26.0
  fs-extra: ^11.3.0
  happy-dom: ^17.4.6
  lint-staged: ^15.5.2
  maybe-types: ^0.2.0
  nolyfill: ^1.0.44
  scss: ^0.2.4
  simple-git-hooks: ^2.13.0
  taze: ^19.0.4
  tslx: ^0.1.1
  type-fest: ^4.41.0
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.1.0
  unplugin-vue-components: ^28.5.0
  vitest: ^3.1.3
