packages:
  - packages/**
  - docs
catalog:
  "@curev/eslint-config": ^0.5.1
  "@iconify-json/carbon": ^1.2.13
  "@tanstack/virtual-core": ^3.13.12
  "@types/fs-extra": ^11.0.4
  "@types/node": ^22.17.2
  "@vitest/coverage-v8": ^3.2.4
  "@vue/test-utils": ^2.4.6
  bumpp: ^10.2.3
  defu: ^6.1.4
  eslint: ^9.33.0
  fs-extra: ^11.3.1
  happy-dom: ^18.0.1
  lint-staged: ^16.1.5
  maybe-types: ^0.2.0
  nolyfill: ^1.0.44
  scss: ^0.2.4
  simple-git-hooks: ^2.13.1
  taze: ^19.1.0
  tslx: ^0.1.1
  type-fest: ^5.0.0
  typescript: ^5.9.2
  unbuild: ^3.6.1
  unocss: ^66.4.2
  unplugin-vue-components: ^29.0.0
  vitest: ^3.2.4
