packages:
  - packages/**
  - docs
catalog:
  "@curev/eslint-config": ^0.6.0
  "@iconify-json/carbon": ^1.2.13
  "@tanstack/virtual-core": ^3.13.12
  "@types/fs-extra": ^11.0.4
  "@types/node": ^22.18.9
  "@vitest/coverage-v8": ^4.0.0
  "@vue/test-utils": ^2.4.6
  bumpp: ^10.3.1
  defu: ^6.1.4
  eslint: ^9.37.0
  fs-extra: ^11.3.2
  happy-dom: ^20.0.0
  lint-staged: ^16.2.3
  maybe-types: ^0.2.0
  nolyfill: ^1.0.44
  scss: ^0.2.4
  simple-git-hooks: ^2.13.1
  taze: ^19.7.0
  tslx: ^0.1.1
  type-fest: ^5.0.1
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unocss: ^66.5.2
  unplugin-vue-components: ^30.0.0
  vitest: ^4.0.0
