/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HiAffix: typeof import('hoci')['HiAffix']
    HiFileUpload: typeof import('hoci')['HiFileUpload']
    HiIcon: typeof import('hoci')['HiIcon']
    HiItem: typeof import('hoci')['HiItem']
    HiPopover: typeof import('hoci')['HiPopover']
    HiSelection: typeof import('hoci')['HiSelection']
    HiSwitch: typeof import('hoci')['HiSwitch']
    HiTabPane: typeof import('hoci')['HiTabPane']
    HiTabs: typeof import('hoci')['HiTabs']
    HiVirtualList: typeof import('hoci')['HiVirtualList']
  }
}
