/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HiAffix: typeof import('hoci')['HiAffix']
    HiFileUpload: typeof import('hoci')['HiFileUpload']
    HiIcon: typeof import('hoci')['HiIcon']
    HiItem: typeof import('hoci')['HiItem']
    HiPopover: typeof import('hoci')['HiPopover']
    HiSelection: typeof import('hoci')['HiSelection']
    HiSwitch: typeof import('hoci')['HiSwitch']
    HiTabPane: typeof import('hoci')['HiTabPane']
    HiTabs: typeof import('hoci')['HiTabs']
    HiVirtualList: typeof import('hoci')['HiVirtualList']
  }
}

// For TSX support
declare global {
  const HiAffix: typeof import('hoci')['HiAffix']
  const HiFileUpload: typeof import('hoci')['HiFileUpload']
  const HiIcon: typeof import('hoci')['HiIcon']
  const HiItem: typeof import('hoci')['HiItem']
  const HiPopover: typeof import('hoci')['HiPopover']
  const HiSelection: typeof import('hoci')['HiSelection']
  const HiSwitch: typeof import('hoci')['HiSwitch']
  const HiTabPane: typeof import('hoci')['HiTabPane']
  const HiTabs: typeof import('hoci')['HiTabs']
  const HiVirtualList: typeof import('hoci')['HiVirtualList']
}